language: node_js

os:
  - linux

node_js:
  - 4
  - 6
  - 8
  - 10
  - 12
  - 14
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install libsnappy-dev
  - sudo pip install python-snappy
